#!/usr/bin/env bash

set -euo pipefail

readonly ROUTING_FILE="${HOME}/.config/i3/workspace-output-routing.conf"
readonly WORKSPACES=(
  "1:I"
  "2:II"
  "3:III"
  "4:IV"
  "5:V"
  "6:VI"
  "7:VII"
  "8:VIII"
  "9:IX"
  "10:X"
)

have_cmd() {
  command -v "$1" >/dev/null 2>&1
}

detect_outputs() {
  active_outputs=()
  primary_output=""
  secondary_output=""

  if have_cmd i3-msg && have_cmd jq; then
    local outputs_json
    outputs_json="$(i3-msg -t get_outputs 2>/dev/null || true)"
    if [[ -n "$outputs_json" ]]; then
      mapfile -t active_outputs < <(
        jq -r '.[] | select(.active == true and .name != "xroot-0") | .name' <<<"$outputs_json"
      )
    fi
  fi

  if [[ "${#active_outputs[@]}" -eq 0 ]]; then
    mapfile -t active_outputs < <(xrandr --listactivemonitors 2>/dev/null | awk 'NR > 1 { print $NF }')
  fi

  if [[ "${#active_outputs[@]}" -eq 0 ]]; then
    mapfile -t active_outputs < <(
      xrandr --query |
        awk '$2 == "connected" { for (i = 3; i <= NF; i++) if ($i ~ /^[0-9]+x[0-9]+\+/) { print $1; break } }'
    )
  fi

  local internal_output=""
  local external_output=""
  local output

  for output in "${active_outputs[@]}"; do
    if [[ -z "$internal_output" && "$output" =~ ^eDP ]]; then
      internal_output="$output"
    fi
  done

  for output in "${active_outputs[@]}"; do
    if [[ "$output" != "$internal_output" ]]; then
      external_output="$output"
      break
    fi
  done

  if [[ -n "$external_output" ]]; then
    primary_output="$external_output"
    secondary_output="$internal_output"
  elif [[ -n "$internal_output" ]]; then
    primary_output="$internal_output"
  elif [[ "${#active_outputs[@]}" -gt 0 ]]; then
    primary_output="${active_outputs[0]}"
  fi
}

build_single_rules() {
  local target="$1"
  local rules=()
  local workspace

  for workspace in "${WORKSPACES[@]}"; do
    rules+=("workspace \"$workspace\" output $target")
  done

  printf '%s\n' "${rules[@]}"
}

build_split_rules() {
  local primary="$1"
  local secondary="$2"
  local rules=()
  local index workspace

  for index in "${!WORKSPACES[@]}"; do
    workspace="${WORKSPACES[$index]}"
    if (( index < 5 )); then
      rules+=("workspace \"$workspace\" output $primary")
    else
      rules+=("workspace \"$workspace\" output $secondary")
    fi
  done

  printf '%s\n' "${rules[@]}"
}

write_rules() {
  local content="$1"
  local tmp_file

  tmp_file="$(mktemp)"
  {
    printf '# Generated by display/routing.sh. Do not edit by hand.\n'
    printf '%s\n' "$content"
  } >"$tmp_file"

  if [[ ! -f "$ROUTING_FILE" ]] || ! cmp -s "$tmp_file" "$ROUTING_FILE"; then
    mv "$tmp_file" "$ROUTING_FILE"
    rules_changed=1
  else
    rm -f "$tmp_file"
    rules_changed=0
  fi
}

normalize_existing_workspaces() {
  if ! have_cmd i3-msg || ! have_cmd jq; then
    return 0
  fi

  local workspaces_json focused_num workspace_name target_output index
  workspaces_json="$(i3-msg -t get_workspaces)"
  focused_num="$(jq -r '.[] | select(.focused) | .num // empty' <<<"$workspaces_json" | head -n 1)"

  for index in "${!WORKSPACES[@]}"; do
    workspace_name="$(jq -r --argjson num "$((index + 1))" '.[] | select(.num == $num) | .name' <<<"$workspaces_json" | head -n 1)"
    [[ -z "$workspace_name" ]] && continue

    if [[ "$workspace_name" != "${WORKSPACES[$index]}" ]]; then
      i3-msg "rename workspace \"$workspace_name\" to \"${WORKSPACES[$index]}\"" >/dev/null || true
    fi

    if [[ "$routing_mode" == "split" && -n "$secondary_target" ]]; then
      if (( index < 5 )); then
        target_output="$primary_target"
      else
        target_output="$secondary_target"
      fi
    else
      target_output="$primary_target"
    fi

    i3-msg "workspace number $((index + 1)); move workspace to output $target_output" >/dev/null || true
  done

  if [[ -n "$focused_num" ]]; then
    i3-msg "workspace number $focused_num" >/dev/null || true
  fi
}

reload_i3_if_needed() {
  if [[ "$reload_if_changed" -eq 1 && "$rules_changed" -eq 1 ]] && have_cmd i3-msg; then
    i3-msg reload >/dev/null || true
  fi
}

routing_mode="${1:-auto}"
reload_if_changed=0
normalize_existing=0
args=()

if (($# > 0)); then
  shift
fi

for arg in "$@"; do
  case "$arg" in
    --reload-if-changed)
      reload_if_changed=1
      ;;
    --normalize)
      normalize_existing=1
      ;;
    *)
      args+=("$arg")
      ;;
  esac
done

detect_outputs

primary_target=""
secondary_target=""
rules_changed=0

case "$routing_mode" in
  auto)
    if [[ -n "$primary_output" && -n "$secondary_output" ]]; then
      routing_mode="split"
      primary_target="$primary_output"
      secondary_target="$secondary_output"
      write_rules "$(build_split_rules "$primary_target" "$secondary_target")"
    elif [[ -n "$primary_output" ]]; then
      routing_mode="single"
      primary_target="$primary_output"
      write_rules "$(build_single_rules "$primary_target")"
    elif [[ "${#active_outputs[@]}" -gt 0 ]]; then
      routing_mode="single"
      primary_target="${active_outputs[0]}"
      write_rules "$(build_single_rules "$primary_target")"
    else
      echo "未能检测到可用显示输出。" >&2
      exit 1
    fi
    ;;
  single)
    primary_target="${args[0]:-$primary_output}"
    if [[ -z "$primary_target" && "${#active_outputs[@]}" -gt 0 ]]; then
      primary_target="${active_outputs[0]}"
    fi
    if [[ -z "$primary_target" ]]; then
      echo "未能确定单屏工作区路由目标输出。" >&2
      exit 1
    fi
    write_rules "$(build_single_rules "$primary_target")"
    ;;
  split)
    primary_target="${args[0]:-$primary_output}"
    secondary_target="${args[1]:-$secondary_output}"
    if [[ -z "$primary_target" || -z "$secondary_target" ]]; then
      echo "未能确定双屏工作区路由目标输出。" >&2
      exit 1
    fi
    write_rules "$(build_split_rules "$primary_target" "$secondary_target")"
    ;;
  *)
    echo "未知模式: $routing_mode" >&2
    exit 1
    ;;
esac

reload_i3_if_needed
if [[ "$normalize_existing" -eq 1 ]]; then
  normalize_existing_workspaces
fi
