#!/usr/bin/env bash

set -euo pipefail

readonly I3_DIR="/home/coisini/.config/i3"
readonly THEMES_DIR="$I3_DIR/themes"
readonly CURRENT_DIR="$THEMES_DIR/current"
readonly STATE_FILE="$I3_DIR/.current-theme"
readonly POLYBAR_CONFIG="/home/coisini/.config/polybar/config.ini"
readonly POLYBAR_LAUNCH="/home/coisini/.config/polybar/launch.sh"
readonly TRAY_APPLETS_LAUNCH="$I3_DIR/tray-applets-launch.sh"
readonly KITTY_CONF="/home/coisini/.config/kitty/kitty.conf"
SKIP_LIVE_POLYBAR="${SKIP_LIVE_POLYBAR:-1}"

die() {
  echo "theme-switcher: $*" >&2
  exit 1
}

theme_dir_for() {
  local id="$1"
  [[ "$id" =~ ^[A-Za-z0-9_-]+$ ]] || die "bad theme id: $id"
  echo "$THEMES_DIR/$id"
}

load_theme() {
  THEME_ID="$1"
  THEME_DIR="$(theme_dir_for "$THEME_ID")"
  [[ -f "$THEME_DIR/theme.conf" ]] || die "missing theme.conf for $THEME_ID"

  # shellcheck source=/dev/null
  source "$THEME_DIR/theme.conf"

  THEME_LABEL="${THEME_LABEL:-$THEME_ID}"
  THEME_ICON="${THEME_ICON:-}"
  WALLPAPER="${WALLPAPER:-wallpaper.png}"

  BAR_BG="${BAR_BG:-#dcd3ca}"
  BG_ALT="${BG_ALT:-#c9bfb4}"
  PANEL="${PANEL:-#f5ebe1}"
  PANEL_ALT="${PANEL_ALT:-#d0c6ba}"
  INK="${INK:-#1a1a1a}"
  INK_SOFT="${INK_SOFT:-#2a2a2a}"
  MUTED="${MUTED:-#6a6258}"
  MUTED_SOFT="${MUTED_SOFT:-#b3a99c}"
  WHITE="${WHITE:-#ffffff}"
  ACCENT="${ACCENT:-#ca7081}"
  ACCENT_SOFT="${ACCENT_SOFT:-$ACCENT}"
  CYAN="${CYAN:-#4f8a82}"
  AQUA="${AQUA:-#6f8f6f}"
  GREEN="${GREEN:-#6f8f6f}"
  YELLOW="${YELLOW:-#b08a4a}"
  ORANGE="${ORANGE:-#c07a4a}"
  PURPLE="${PURPLE:-#9a6f8a}"
  RED="${RED:-$ACCENT}"
  LOCK_BG="${LOCK_BG:-$PANEL}"

  [[ -f "$THEME_DIR/$WALLPAPER" ]] || die "missing wallpaper: $THEME_DIR/$WALLPAPER"
}

theme_entries() {
  local dir id label icon wallpaper
  for dir in "$THEMES_DIR"/*; do
    [[ -d "$dir" ]] || continue
    [[ "$(basename "$dir")" == "current" ]] && continue
    [[ -f "$dir/theme.conf" ]] || continue
    id="$(basename "$dir")"
    (
      # shellcheck source=/dev/null
      source "$dir/theme.conf"
      label="${THEME_LABEL:-$id}"
      icon="${THEME_ICON:-}"
      wallpaper="${WALLPAPER:-wallpaper.png}"
      [[ -f "$dir/$wallpaper" ]] || exit 0
      printf '%s\t%s %s\n' "$id" "$icon" "$label"
    )
  done | sort
}

current_theme() {
  if [[ -f "$STATE_FILE" ]]; then
    cat "$STATE_FILE"
    return
  fi

  echo "beige"
}

prepare_current_dir() {
  if [[ -L "$CURRENT_DIR" ]]; then
    rm -f "$CURRENT_DIR"
  fi
  mkdir -p "$CURRENT_DIR"
}

render_i3_colors() {
  cat > "$THEME_DIR/i3-colors.conf" <<EOF
client.focused          $INK $INK $PANEL $ACCENT $INK
client.focused_inactive $BAR_BG $BAR_BG $INK $BAR_BG $BAR_BG
client.unfocused        $BG_ALT $BAR_BG $MUTED $BG_ALT $BG_ALT
client.urgent           $RED $RED $PANEL $RED $RED
client.placeholder      $BAR_BG $BAR_BG $INK $BAR_BG $BAR_BG
client.background       $PANEL
EOF
}

render_kitty_conf() {
  cat > "$THEME_DIR/kitty.conf" <<EOF
background_opacity 1.0
background_image none
background              $PANEL
foreground              $INK_SOFT
cursor                  $INK
cursor_text_color       $PANEL
selection_background    $ACCENT
selection_foreground    $PANEL
active_tab_foreground   $PANEL
active_tab_background    $INK
inactive_tab_foreground $MUTED
inactive_tab_background $BAR_BG
tab_bar_background      $BAR_BG

color0  $INK_SOFT
color8  $MUTED
color1  $RED
color9  $RED
color2  $GREEN
color10 $GREEN
color3  $YELLOW
color11 $YELLOW
color4  $CYAN
color12 $CYAN
color5  $PURPLE
color13 $PURPLE
color6  $AQUA
color14 $AQUA
color7  $PANEL
color15 $WHITE
EOF
}

render_control_center_css() {
  cat > "$I3_DIR/control-center.css" <<EOF
/* Generated by theme-switcher.sh from $THEME_ID */
.cc-window { background-color: transparent; }

.cc-panel {
  background-color: $PANEL;
  border-radius: 22px;
  padding: 16px;
  box-shadow: 0 16px 44px rgba(26,26,26,0.20);
}

.np-tile { background-color: $INK; border-radius: 18px; padding: 14px; }
.np-title  { color: $PANEL; font-weight: 700; font-size: 14px; }
.np-artist { color: $MUTED_SOFT; font-size: 12px; }
.np-ctl { color: $PANEL; font-size: 16px; background: none; border: none; box-shadow: none; padding: 4px; }
.np-ctl:hover { opacity: 0.7; }

.art { border-radius: 12px; }
.art-fallback {
  border-radius: 12px;
  background-image: linear-gradient(135deg, $ACCENT 0%, $ACCENT_SOFT 50%, $PANEL 100%);
}

.tile { background-color: $BAR_BG; border-radius: 18px; padding: 14px; }
.tile-on { background-color: $ACCENT; }
.tile-title { color: $INK; font-weight: 700; font-size: 14px; }
.tile-sub   { color: $MUTED; font-size: 11px; }
.tile-on .tile-title { color: $PANEL; }
.tile-on .tile-sub   { color: $PANEL; }
.tile-icon    { color: $MUTED; font-size: 18px; }
.tile-icon-on { color: $PANEL; font-size: 18px; }

.spk-btn { background: none; border: none; box-shadow: none; color: $INK; font-size: 18px; padding: 4px 8px; }
.spk-btn:hover { opacity: 0.7; }
.vol-scale trough { min-height: 26px; border-radius: 16px; background-color: $BAR_BG; }
.vol-scale highlight { min-height: 26px; border-radius: 16px; background-color: $INK; }
.vol-scale slider { min-width: 2px; min-height: 2px; background-color: transparent; }

.pwr-btn {
  background-color: $BAR_BG; border: none; box-shadow: none;
  border-radius: 14px; color: $INK; font-size: 18px; padding: 10px 0;
}
.pwr-btn:hover { background-color: $PANEL_ALT; }
.pwr-danger { color: $RED; }
.pwr-confirm { background-color: $ACCENT; color: $PANEL; }
EOF
}

render_music_panel_css() {
  cat > "$I3_DIR/music-panel.css" <<EOF
/* Generated by theme-switcher.sh from $THEME_ID */
.music-window { background-color: transparent; }

.card {
  border-radius: 26px;
  padding: 18px;
  box-shadow: 0 14px 40px rgba(26,26,26,0.18);
}

.art { border-radius: 16px; }
.art-fallback {
  border-radius: 16px;
  background-image: linear-gradient(135deg, $ACCENT 0%, $ACCENT_SOFT 45%, $PANEL 100%);
}

.title  { font-weight: 700; }
.artist { font-size: 12px; }

.scrub trough { min-height: 5px; border-radius: 3px; background-color: $BG_ALT; }
.scrub highlight { min-height: 5px; border-radius: 3px; background-color: $INK; }
.scrub slider {
  min-width: 12px; min-height: 12px; border-radius: 50%;
  background-color: $INK; margin: -5px;
}
.time { font-size: 11px; color: $MUTED; }

.ctl-btn {
  background: none; border: none; box-shadow: none; padding: 6px;
  color: $INK; font-size: 18px;
}
.ctl-btn:hover { opacity: 0.7; }
.ctl-play {
  border-radius: 50%; background-color: $INK; color: $PANEL;
  min-width: 48px; min-height: 48px; font-size: 20px;
}
.skin-btn {
  background: none; border: none; box-shadow: none;
  color: $MUTED; font-size: 13px; padding: 2px 6px;
}
.skin-btn:hover { color: $ACCENT; }

.skin-a { background-color: $PANEL; }
.skin-a .title  { color: $INK; font-size: 19px; }
.skin-a .artist { color: $MUTED; }

.skin-b { background-color: $PANEL; }
.skin-b .title  { color: $INK; font-size: 16px; }
.skin-b .artist { color: $MUTED; }

.skin-c { background-color: $INK; }
.skin-c .title  { color: $PANEL; font-size: 15px; }
.skin-c .artist { color: $MUTED_SOFT; }
.skin-c .ctl-btn { color: $PANEL; }
.skin-c .ctl-play { background-color: $ACCENT; color: $INK; }
.skin-c .scrub highlight { background-color: $ACCENT; }
.skin-c .skin-btn { color: $MUTED_SOFT; }
.skin-c .time { color: $MUTED_SOFT; }
EOF
}

render_polybar_config() {
  [[ -f "$POLYBAR_CONFIG" ]] || return 0

  local tmp menu_content
  tmp="$(mktemp)"
  menu_content="%{T4}%{F$INK}%{F-}%{T-}%{T1}%{B$INK}%{F$PANEL} 󰣛 %{F-}%{B-}%{T-}%{T4}%{F$INK}%{F-}%{T-}"

  awk \
    -v bg="$BAR_BG" -v bg_alt="$BG_ALT" -v fg="$INK" -v dim="$MUTED" \
    -v ink="$INK" -v cream="$PANEL" -v cyan="$CYAN" -v aqua="$AQUA" \
    -v green="$GREEN" -v yellow="$YELLOW" -v orange="$ORANGE" \
    -v red="$RED" -v purple="$PURPLE" -v menu="$menu_content" '
      /^\[colors\]$/ {
        print
        print "background = " bg
        print "background-alt = " bg_alt
        print "foreground = " fg
        print "foreground-dim = " dim
        print "ink = " ink
        print "cream = " cream
        print "cyan = " cyan
        print "aqua = " aqua
        print "green = " green
        print "yellow = " yellow
        print "orange = " orange
        print "red = " red
        print "purple = " purple
        in_colors = 1
        next
      }
      in_colors && /^\[/ { in_colors = 0 }
      in_colors { next }
      /^\[module\/menu\]$/ { in_menu = 1; print; next }
      /^\[module\// && !/^\[module\/menu\]$/ { in_menu = 0; print; next }
      in_menu && /^content = / { print "content = " menu; next }
      { print }
    ' "$POLYBAR_CONFIG" > "$tmp"

  mv "$tmp" "$POLYBAR_CONFIG"
}

ensure_kitty_include() {
  [[ -f "$KITTY_CONF" ]] || return 0

  if grep -q '^include /home/coisini/.config/i3/themes/current/kitty.conf$' "$KITTY_CONF"; then
    return 0
  fi

  if grep -q '^include /home/coisini/.config/i3/themes/beige/kitty-beige.conf$' "$KITTY_CONF"; then
    sed -i 's|^include /home/coisini/.config/i3/themes/beige/kitty-beige.conf$|include /home/coisini/.config/i3/themes/current/kitty.conf|' "$KITTY_CONF"
  else
    printf '\ninclude /home/coisini/.config/i3/themes/current/kitty.conf\n' >> "$KITTY_CONF"
  fi
}

stop_tray_clients() {
  pkill -x nm-applet 2>/dev/null || true
  pkill -x pasystray 2>/dev/null || true
  pkill -x blueman-applet 2>/dev/null || true
  pkill -x cc-switch 2>/dev/null || true
  pkill -f '^/usr/bin/python3 /usr/bin/ulauncher --hide-window' 2>/dev/null || true
  pgrep -f '^/opt/todesk/bin/ToDesk$' | xargs -r kill -9 2>/dev/null || true
  sleep 0.2
}

start_tray_clients() {
  if command -v cc-switch >/dev/null 2>&1; then
    /usr/bin/cc-switch >/tmp/cc-switch.log 2>&1 &
    sleep 0.4
  fi
  if command -v ulauncher >/dev/null 2>&1; then
    /usr/bin/ulauncher --hide-window --hide-window >/tmp/ulauncher.log 2>&1 &
    sleep 0.4
  fi
  if command -v nm-applet >/dev/null 2>&1; then
    /usr/bin/dbus-launch nm-applet --sm-disable >/tmp/nm-applet.log 2>&1 &
    sleep 0.4
  fi
  if command -v pasystray >/dev/null 2>&1; then
    pasystray >/tmp/pasystray.log 2>&1 &
    sleep 0.4
  fi
  if command -v blueman-applet >/dev/null 2>&1; then
    blueman-applet >/tmp/blueman-applet.log 2>&1 &
    sleep 0.4
  fi
}

stop_polybar() {
  pkill -x polybar 2>/dev/null || true
  pgrep -f '^/bin/sh -c ~/.config/polybar/scripts/i3-workspaces.sh$|^bash /home/coisini/.config/polybar/scripts/i3-workspaces.sh$' \
    | xargs -r kill 2>/dev/null || true
}

launch_polybar() {
  [[ -x "$POLYBAR_LAUNCH" ]] || return 0

  if command -v i3-msg >/dev/null 2>&1; then
    i3-msg "exec --no-startup-id bash $POLYBAR_LAUNCH" >/tmp/polybar-theme-switch.log 2>&1 || true
    return 0
  fi

  bash "$POLYBAR_LAUNCH" >/tmp/polybar-theme-switch.log 2>&1 || true
}

launch_tray_clients() {
  if [[ -x "$TRAY_APPLETS_LAUNCH" ]] && command -v i3-msg >/dev/null 2>&1; then
    i3-msg "exec --no-startup-id $TRAY_APPLETS_LAUNCH" >/tmp/tray-applets-theme-switch.log 2>&1 || true
    return 0
  fi

  if [[ -x "$TRAY_APPLETS_LAUNCH" ]]; then
    "$TRAY_APPLETS_LAUNCH" >/tmp/tray-applets-theme-switch.log 2>&1 || true
    return 0
  fi

  start_tray_clients
}

hide_todesk_windows() {
  command -v jq >/dev/null 2>&1 || return 0
  i3-msg -t get_tree \
    | jq -r '.. | objects | select(.window_properties.class? == "ToDesk") | .id' \
    | while read -r con_id; do
        [[ -n "$con_id" ]] && i3-msg "[con_id=\"$con_id\"] move scratchpad" >/dev/null 2>&1 || true
      done
}

apply_wallpaper_with_bar_restart() {
  stop_tray_clients
  stop_polybar

  if command -v feh >/dev/null 2>&1; then
    feh --no-fehbg --bg-fill "$CURRENT_DIR/wallpaper.png" || true
  fi

  launch_polybar
  sleep 1
  launch_tray_clients
  sleep 1
  hide_todesk_windows
}

apply_theme() {
  load_theme "$1"

  render_i3_colors
  render_kitty_conf
  render_control_center_css
  render_music_panel_css
  if [[ "$SKIP_LIVE_POLYBAR" != "1" ]]; then
    render_polybar_config
  fi
  ensure_kitty_include

  prepare_current_dir
  cp -f "$THEME_DIR/theme.conf" "$CURRENT_DIR/theme.conf"
  cp -f "$THEME_DIR/$WALLPAPER" "$CURRENT_DIR/wallpaper.png"
  cp -f "$THEME_DIR/i3-colors.conf" "$CURRENT_DIR/i3-colors.conf"
  cp -f "$THEME_DIR/kitty.conf" "$CURRENT_DIR/kitty.conf"
  printf '%s\n' "$THEME_ID" > "$STATE_FILE"

  if [[ "${APPLY_THEME_WALLPAPER:-1}" == "1" ]]; then
    apply_wallpaper_with_bar_restart
  fi

  if [[ "${APPLY_THEME_KITTY_SIGNAL:-1}" == "1" ]]; then
    pkill -USR1 kitty 2>/dev/null || true
  fi

  echo "$THEME_ID"
}

show_menu() {
  command -v rofi >/dev/null 2>&1 || die "rofi not found"

  local selected id
  selected="$(theme_entries | rofi -dmenu -i -p "Theme" \
    -theme-str 'listview { lines: 8; }' 2>/dev/null || true)"
  [[ -z "$selected" ]] && exit 0

  id="${selected%%$'\t'*}"
  apply_theme "$id"
}

case "${1:-menu}" in
  menu)
    show_menu
    ;;
  apply|set)
    apply_theme "${2:-}"
    ;;
  current)
    current_theme
    ;;
  list)
    theme_entries
    ;;
  render-polybar)
    load_theme "$(current_theme)"
    render_polybar_config
    ;;
  *)
    echo "usage: $0 [menu|list|current|apply THEME_ID]" >&2
    exit 2
    ;;
esac
